import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "io.github.blzkz.formpdfreader"
    compileSdk = 36

    defaultConfig {
        applicationId = "io.github.blzkz.formpdfreader"
        minSdk = 26
        // Google Play requires API 36 for new apps and updates (August 2026).
        targetSdk = 36
        versionCode = 6
        versionName = "0.3.3"
        // The Rust core and PDFium are built for arm64 (scripts/android/build-rust.sh).
        ndk { abiFilters += listOf("arm64-v8a") }
    }

    // Release signing: the upload key for Google Play, from the environment
    // (the CI decodes it from the repository secrets; see
    // scripts/android/crear-clave-de-subida.sh). Without it, local and pull
    // request builds are signed with the debug key.
    val keystore = System.getenv("ANDROID_KEYSTORE")?.takeIf { it.isNotBlank() && file(it).exists() }
    signingConfigs {
        if (keystore != null) {
            create("upload") {
                storeFile = file(keystore)
                storeType = "pkcs12"
                storePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias = System.getenv("ANDROID_KEY_ALIAS")
                keyPassword = System.getenv("ANDROID_KEY_PASSWORD") ?: System.getenv("ANDROID_KEYSTORE_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            signingConfig = signingConfigs.findByName("upload") ?: signingConfigs.getByName("debug")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // Kotlin bindings generated by uniffi (scripts/android/build-rust.sh).
    sourceSets["main"].java.srcDir("src/generated/kotlin")
    // Licences shown in Settings (scripts/android/build-rust.sh).
    sourceSets["main"].assets.srcDir("src/generated/assets")

    packaging {
        jniLibs { useLegacyPackaging = true }
    }
}

kotlin {
    compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
}

dependencies {
    // uniffi's Kotlin bindings call the Rust library through JNA.
    implementation("net.java.dev.jna:jna:5.15.0@aar")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.core:core-ktx:1.15.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.recyclerview:recyclerview:1.3.2")
}
